import '../globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type Props = {
  children: React.ReactNode;
};
export default function Layout(props: Props) {
  return (
    <div>
      <p>현대 카드 무이자 이벤트중</p>
      {props.children}
    </div>
  );
}
